version: '3.8'
services:
   postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=myPassword
      - PGDATA= /data/postgres
    volumes:
      - postgres-storage:/data/postgres
    networks:
      - abp-network 
    ports:
      - "5432:5432"
   redis:
    image: redis:alpine
    container_name: redis
    networks:
      - abp-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      
volumes:
  postgres-storage:
    name: doohlink-postgres
    driver: local
networks:
  abp-network:
    name: doohlink-network
    driver: bridge